### ISSUE TITLE
License file

### ISSUE THREAD

**Issue by KristjanESPERANTO** [bnitkin/MMM-transitfeed#4]
It would be nice if you would add a license file. MagicMirror and most other modules use the MIT license, here is an example: https://github.com/MagicMirrorOrg/MagicMirror/blob/master/LICENSE.md :slightly_smiling_face:

**Comment by bnitkin** [comment]
Sure! I can do that.

**Comment by KristjanESPERANTO** [comment]
Nice. Thanks! :smiley:
